// import {
//   ClerkProvider,
//   SignInButton,
//   SignedIn,
//   SignedOut,
//   UserButton
// } from '@clerk/nextjs'
import {Comic_Neue} from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const comic = Comic_Neue({
  weight: "700",
  variable: "--font-comic-neue", // Corrected variable name
  style: "normal",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body
        className={`${comic.variable}`}
      >
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
